/**
 * Emits a proof built by the TypeScript side so Foundry can check that Solidity
 * decodes it to the same Verdict.
 *
 * The seal is signed in TS with viem and verified in Solidity with ECDSA over
 * `abi.decode`. Nothing guarantees those two agree on encoding except a test that
 * actually crosses the boundary, so this fixture is regenerated and asserted in CI
 * rather than eyeballed once.
 *
 *   pnpm --filter @acu/seal gen-fixture
 */
import { writeFileSync, mkdirSync } from "node:fs";
import { privateKeyToAccount } from "viem/accounts";
import { keccak256, toHex } from "viem";
import { signSealA, signSealB, buildStubProof, toVerdict, sealDigest } from "../src/index.js";
import type { SealA, SealB, Unsigned } from "../src/index.js";

const AGENT_B_KEY = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d" as const;
const AGENT_A_KEY = "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a" as const;

const agentB = privateKeyToAccount(AGENT_B_KEY);
const agentA = privateKeyToAccount(AGENT_A_KEY);

const TOKEN = "0x00000000000000000000000000000000000000ca" as const;
const ISSUED = 1_756_000_000;
const EXPIRES = ISSUED + 86_400;

const unsignedB: Unsigned<SealB> = {
  version: 1,
  type: "audit",
  agentId: "2",
  subject: TOKEN,
  request: keccak256(toHex("fixture-request")),
  inference: {
    model: "0gm-1.0-35b-a3b",
    trustMode: "verified",
    providerAddress: "0xd9966e13a6026fcca4b13e7ff95c94de268c471c",
    promptHash: keccak256(toHex("prompt")),
    responseHash: keccak256(toHex("response")),
    teeAttestation: {
      chatId: "fixture-chat",
      teeVerified: true,
      teeSignerAddress: "0x3333333333333333333333333333333333333333",
      signature: "0xabcd",
      signedTextHash: keccak256(toHex("response")),
      signatureEndpoint: "https://provider.example/v1/proxy/signature/fixture-chat",
    },
  },
  findings: ["upgradeable_proxy", "hidden_blacklist"],
  verdict: { action: "ALLOW", maxLtvBps: 7500 },
  issuedAt: ISSUED,
  expiresAt: EXPIRES,
};

const sealB = await signSealB(unsignedB, agentB);

const unsignedA: Unsigned<SealA> = {
  version: 1,
  type: "underwriting",
  agentId: "1",
  subject: TOKEN,
  delegations: [
    {
      agentId: "2",
      service: "code-audit",
      priceAtomic: "10000",
      network: "eip155:84532",
      settlementTx: keccak256(toHex("settle")),
      seal: sealB,
      sealVerified: true,
    },
  ],
  ownAnalysis: {
    liquidityDepthUsd: "125000",
    top10HolderPct: 62.4,
    sourceHash: keccak256(toHex("source")),
  },
  verdict: { action: "ALLOW", maxLtvBps: 7500, expiresAt: EXPIRES },
};

const sealA = await signSealA(unsignedA, agentA);
const verdict = toVerdict(sealA);
const proof = await buildStubProof(sealA, agentA);

const out = {
  note: "Generated by packages/seal/scripts/gen-fixture.ts. Regenerate if the Verdict layout changes.",
  signer: agentA.address,
  token: TOKEN,
  proof,
  expected: {
    subject: verdict.subject,
    action: verdict.action,
    maxLtvBps: verdict.maxLtvBps,
    expiresAt: Number(verdict.expiresAt),
    sealHash: verdict.sealHash,
    agentId: Number(verdict.agentId),
    delegationDepth: verdict.delegationDepth,
  },
  sealADigest: sealDigest(sealA as unknown as Record<string, unknown>),
};

const dir = new URL("../../../contracts/test/fixtures/", import.meta.url).pathname;
mkdirSync(dir, { recursive: true });
writeFileSync(`${dir}stub-proof.json`, JSON.stringify(out, null, 2) + "\n");
console.log(`wrote ${dir}stub-proof.json`);
console.log(`  signer   ${out.signer}`);
console.log(`  sealHash ${out.expected.sealHash}`);
console.log(`  proof    ${proof.length} chars`);
